source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'AFNetworking', '~> 2.0'
pod 'CHTStickerView', '~> 0.5'
pod 'SDWebImage', '~> 3.7.1'
pod 'Parse', '~> 1.5.0'
pod 'SVProgressHUD', :head
pod 'RevMob', '~> 7.5.5'
pod 'FlurrySDK', '~> 5.4.0'
pod 'ECSlidingViewController', '~> 2.0.3'
pod 'FCVerticalMenu'
pod 'PQFCustomLoaders', '~> 0.0.1'
pod 'Facebook-iOS-SDK', '~> 3.21.1'
pod 'AMPopTip'
